defaults:
  - trainer
  - _self_
  - override /env: csgo
  - override /agent: sana_csgo

wandb:
  mode: online
  project: diamond-sana-csgo
  name: null

auto_encode_latents: true
use_cached_latents: true

static_dataset:
  path: ${env.path_data}
  ignore_sample_weights: true

visual_sampling:
  should: true
  every_steps: 500
  num_rollout_frames: 5
  episode_id: 0
  segment_start: 100

training:
  num_final_epochs: 50
  cache_in_ram: true
  num_workers_data_loaders: 6
  dataloader_prefetch_factor: 4
  model_free: false
  compile_wm: false
  compile_denoiser: true

world_model_env:
  horizon: 15
  num_batches_to_preload: 32
  diffusion_sampler: null
  latent_sampler:
    _target_: models.diffusion.LatentSamplerConfig
    num_steps_denoising: 20
    flow_shift: 3.0
    num_train_timesteps: 1000
    store_trajectory: false
    use_amp: true

denoiser:
  training:
    batch_size: 8
    grad_acc_steps: 1
    steps_first_epoch: 5000
    steps_per_epoch: 400
    num_autoregressive_steps: 1
    sample_weights: null
